name: 'hospital_datalake'
version: '1.0.0'

profile: 'hospital_spark'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  hospital_datalake:
    +materialized: table
    +file_format: iceberg
    # All models in models/staging will be saved to the 'staging' database
    staging:
      +schema: staging
      
    # All models in models/marts will be saved to the 'marts' database
    marts:
      +schema: marts